### ISSUE TITLE
Problem on running detect3 function

### ISSUE THREAD

**Issue by geografif** [robwschlegel/heatwave3#1]
I have a NetCDF file representing the SST variable from OSTIA.
I tried to run the following code:

```
mhw_cube <- detect3(file_in = system.file("extdata/ostia_sst_1982-2023.nc", package = "heatwave3"),
                    return_type = "df", clim_period = c("1983-01-01", "2022-12-31"))
```

But it says that : Error: [rast] filename is empty. Provide a valid filename

When I read the file as NetCDF file (with netcdf4::nc_open) and run the above code, it said:
*Error in methods::as(x, "SpatRaster") : no method or default for coercing “ncdf4” to “SpatRaster”*

When I read the file as SpatRast (with terra::rast), it said:
*-Aggregate function missing, defaulting to 'length'
-Error: [writeStart] failed writing GTiff file
In addition: Warning messages:
1: [readValues] raster has no values*

Here is the link to my NetCDF file and I hope you can help me: https://drive.google.com/file/d/1fNTxsBTwJUk9XJmhEAic_Kh1RaZzz6UQ/view?usp=sharing

Thanks in advance!

**Comment by robwschlegel** [comment]
Hello Afif,
The example code provided in the `heatwave3` documentation loads a file stored in the `extdata/` folder within the `heatwaveR` folder that was saved to your computer when you installed the libray. To load your own file, please rather provide the pathway to where your file is located on your computer.

For example:
```
mhw_cube <- detect3(file_in = "file_location/ostia_sst_1982-2023.nc", return_type = "df", clim_period = c("1983-01-01", "2022-12-31"))
```

**Comment by geografif** [comment]
Hi, thank you for your prompt response.

I set the working directory to D:/cpo/ and the .nc file is inside the cpo folder. I rewrote the script as follows:

```
mhw_cube <- detect3(file_in = system.file("ostia_sst_1982-2023.nc", package = "heatwave3"),
                    return_type = "df", clim_period = c("1983-01-01", "2022-12-31"))
```

After defining the proper file location, I still got error as follows:
*Error: [rast] filename is empty. Provide a valid filename*

Wondering if I modified the script correctly.

**Comment by robwschlegel** [comment]
Hello,
This is incorrect `system.file("ostia_sst_1982-2023.nc", package = "heatwave3")`

Rather:
```
mhw_cube <- detect3(file_in = "D:/cpo/ostia_sst_1982-2023.nc", return_type = "df", clim_period = c("1983-01-01", "2022-12-31"))
```

**Comment by geografif** [comment]
Thank you.

Unfortunately, I still got the following error:
![error_detect3](https://github.com/robwschlegel/heatwave3/assets/48111760/136e811f-73fa-4bd1-88e8-bdb747862866)

I also tried with the .nc data on data-raw folder, but got the following error:
![image](https://github.com/robwschlegel/heatwave3/assets/48111760/5fda2401-7262-43c1-a2f3-bb5d0b4e6e47)

**Comment by robwschlegel** [comment]
Hello,
If you can upload your OSTIA NetCDF file to this link I will look into it this week:
https://e.pcloud.link/publink/show?code=kZt7TeZWEqSd2Qhfc4FcDHAnYtcv0BtaJF7

**Comment by geografif** [comment]
Files uploaded. Thank you.

**Comment by robwschlegel** [comment]
Hello,
Thank you for uploading the file.
The `heatwave3` package is still very much in development and has only been tested against some very narrow use cases. For the OSTIA file you uploaded, the primary issue was that it contained land pixels (i.e. Nan values). This confused the raster calculations. This issue was corrected in the current version of the package, which you can reinstall.

However, the detection of MHWs using the algorithm in this package is only meant to be run on daily data. The OSTIA file in question is hourly. So I added a bit of code that will automagically detect hourly data and convert them to daily.

Unfortunately that is as far as I could get with the troubleshooting for your file because the `terra` package, which is used to handle NetCDF files here, does not recognise the coordinates within your NetCDF file. Therefore I would recommend that you search for how to format NetCDF files for `terra`, re-download the OSTIA data from a different source, or simply use the `heatwaveR` package.

All the best,
-Robert

**Comment by geografif** [comment]
I updated the package and tried with the NetCDF data inside the data-raw folder on the repository and received a new error message:
![image](https://github.com/robwschlegel/heatwave3/assets/48111760/a9ee9ff5-f783-407d-8ef2-a0a402c75b3d)

**Comment by robwschlegel** [comment]
Please update to the newest version of `heatwaveR` using:
```
devtools::install_github("robwschlegel/heatwaveR")
```
Generally speaking, when first encountering errors in code, update packages then try again.
